a = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaços? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print('É alfanumérico? {}'.format(a.isalnum()))
print('Está em maiúsculas? {}'.format(a.isupper()))
print('Está em minusculas? {}'.format(a.islower()))
print('Está capitalizada? {}'.format(a.istitle()))
